export const PATHS = {
  ROOT: "/",
  LOGIN: "/login",
  DASHBOARD: "/",
  INVENTORIZATION: "/inventorization",
  INVENTORIZATION_DETAIL: (id) => `/inventorization/${id}`,
  TRANSFER_LIST: "/transfer-list",
  TRANSFER_DETAIL: (id) => `/transfer/${id}`,
  RECEIVE: "/receive",
  RECEIVE_DETAIL: (id) => `/receive/${id}`,
  SALES: "/sales",
  SALES_PRICE_LISTS: "/sales/price-lists",
  SALES_PRICE_LIST_DETAIL: (id) => `/sales/price-lists/${id}`,
  REPORT: "/report",
  USERS: "/users",
  USERS_WEBSITE_USERS: "/users/website-users",
  USERS_WEBSITE_ROLES: "/users/website-roles",
  USERS_POCKET_USERS: "/users/pocket-users",
  USERS_POCKET_ROLES: "/users/pocket-roles",
  LOGIN_ACCESS: "/login-access",
  API: "/api",
  SETTINGS: "/settings",
  SETTINGS_WAREHOUSES: "/settings/warehouses",
  ROLES_PERMISSIONS: "/roles-permissions",
};
